name: 'Download libraries'
description: 'Download files necessary for compilation and testing'
inputs:
  download-googletest:
    type: boolean
    description: 'Download googletest'
    default: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install build tools
      run: |
        sudo apt-get update -y
        sudo apt-get install gcc-10 g++-10 cmake build-essential -y
      shell: bash

    - name: Install Boost
      run: sudo apt-get install libboost-all-dev -y
      shell: bash

    - name: Make lib directory
      run: |
        mkdir -p lib
      shell: bash

    - name: Download googletest
      uses: ./.github/composite-actions/download-library
      with:
        directory: googletest
        download-command: git clone https://github.com/google/googletest/ --branch release-1.12.1 --depth 1
      if: inputs.download-googletest != 'false'

    - name: Download easyloggingpp
      uses: ./.github/composite-actions/download-library
      with:
        directory: easyloggingpp
        download-command: git clone https://github.com/amrayn/easyloggingpp/ --branch v9.97.0 --depth 1

