name: Codestyle
on:
  push:
    branches:
      - main
jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pull clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-14
      - name: Check formatting
        run: |
          formatterOutput=$( git diff -U0 origin/$GITHUB_BASE_REF...HEAD | clang-format-diff-14 -p 1)

          if [ "$formatterOutput" != "" ]
          then
            echo ":x: :x: :x:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`c++" >> $GITHUB_STEP_SUMMARY
            echo "$formatterOutput" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "$formatterOutput"
            exit 1
          fi

          echo "$formatterOutput"
          echo "### $formatterOutput :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY