name: CMake
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        uses: ./.github/composite-actions/download-libraries
      - name: Init easylogging++
        run: git submodule update --init --recursive
      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Test
        working-directory: ${{github.workspace}}/build/target
        shell: bash
        run: ./Beta-reduction_test
